apiVersion: v1
kind: ConfigMap
metadata:
  name: basb-config
data:
  # 环境配置
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  
  # API 服务配置
  API_PORT: "3000"
  API_RATE_LIMIT: "100"
  API_TIMEOUT: "30000"
  API_CORS_ORIGIN: "*"
  
  # 知识图谱服务配置
  KNOWLEDGE_GRAPH_PORT: "3001"
  KNOWLEDGE_GRAPH_MAX_NODES: "10000"
  KNOWLEDGE_GRAPH_MAX_LINKS: "50000"
  
  # 文档处理服务配置
  DOCUMENT_PROCESSING_PORT: "3002"
  DOCUMENT_MAX_SIZE: "50MB"
  DOCUMENT_SUPPORTED_TYPES: "pdf,docx,txt,md,html,epub"
  DOCUMENT_STORAGE_PATH: "/app/storage/documents"
  
  # 搜索服务配置
  SEARCH_PORT: "3003"
  SEARCH_INDEX_REFRESH_INTERVAL: "30m"
  SEARCH_MAX_RESULTS: "100"
  
  # AI 服务配置
  AI_SERVICE_PORT: "3004"
  AI_MODEL_CACHE_PATH: "/app/models"
  AI_DEFAULT_MODEL: "gpt-3.5-turbo"
  AI_REQUEST_TIMEOUT: "60000"
  
  # 监控配置
  PROMETHEUS_METRICS_PATH: "/metrics"
  METRICS_COLLECTION_INTERVAL: "15s"
  
  # 日志配置
  LOG_FORMAT: "json"
  LOG_RETENTION_DAYS: "30"
  
  # 缓存配置
  CACHE_TTL: "3600"
  CACHE_CHECK_PERIOD: "600"
  
  # 会话配置
  SESSION_TTL: "86400"
  
  # 安全配置
  JWT_EXPIRATION: "86400"
  PASSWORD_HASH_ROUNDS: "10"
  
  # 业务配置
  MAX_NOTES_PER_USER: "10000"
  MAX_TAGS_PER_USER: "500"
  MAX_PROJECTS_PER_USER: "100"
  MAX_DOCUMENTS_PER_USER: "1000"
  
  # 备份配置
  BACKUP_SCHEDULE: "0 0 * * *"
  BACKUP_RETENTION_DAYS: "30"
---
apiVersion: v1
kind: Secret
metadata:
  name: basb-secrets
type: Opaque
stringData:
  # 数据库凭证
  MONGODB_URI: "mongodb://basb_user:password@mongodb:27017/basb"
  MONGODB_ROOT_USERNAME: "root"
  MONGODB_ROOT_PASSWORD: "rootpassword"
  MONGODB_EXPORTER_URI: "mongodb://root:rootpassword@localhost:27017/admin"
  REDIS_URI: "redis://:redispassword@redis:6379/0"
  REDIS_PASSWORD: "redispassword"
  
  # API 密钥
  JWT_SECRET: "your-jwt-secret-key-change-in-production"
  COOKIE_SECRET: "your-cookie-secret-key-change-in-production"
  
  # 外部服务 API 密钥
  OPENAI_API_KEY: "your-openai-api-key"
  HUGGINGFACE_API_KEY: "your-huggingface-api-key"
  
  # 监控和日志凭证
  ELASTICSEARCH_PASSWORD: "elasticpassword"
  GRAFANA_ADMIN_USER: "admin"
  GRAFANA_ADMIN_PASSWORD: "adminpassword"
  
  # SMTP 配置
  SMTP_HOST: "smtp.example.com"
  SMTP_PORT: "587"
  SMTP_USER: "notifications@example.com"
  SMTP_PASSWORD: "smtppassword"
  SMTP_FROM: "BASB System <notifications@example.com>"
  
  # 存储凭证
  STORAGE_ACCESS_KEY: "your-storage-access-key"
  STORAGE_SECRET_KEY: "your-storage-secret-key"
  
  # 备份凭证
  BACKUP_ENCRYPTION_KEY: "your-backup-encryption-key"