{
 "title": "系统监控",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU 使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU 使用率 - {{instance}}"
    }
   ]
  },
  {
   "title": "系统负载",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1{}", "legendFormat": "1分钟负载 - {{instance}}" },
    { "expr": "node_load5{}", "legendFormat": "5分钟负载 - {{instance}}" },
    { "expr": "node_load15{}", "legendFormat": "15分钟负载 - {{instance}}" }
   ]
  },
  {
   "title": "内存使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - ((node_memory_MemAvailable_bytes{} or (node_memory_Buffers_bytes{} + node_memory_Cached_bytes{} + node_memory_MemFree_bytes{})) / node_memory_MemTotal_bytes{}))",
     "legendFormat": "内存使用率 - {{instance}}"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!~\"tmpfs|fuse.lxcfs|squashfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!~\"tmpfs|fuse.lxcfs|squashfs\"})",
     "legendFormat": "磁盘使用率 (/) - {{instance}}"
    }
   ]
  },
  {
   "title": "网络流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!~\"lo|veth.*\"}[5m])",
     "legendFormat": "接收 - {{instance}} - {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device!~\"lo|veth.*\"}[5m])",
     "legendFormat": "发送 - {{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "活跃的 Systemd 服务",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "node_systemd_unit_state{state=\"active\"}"
    }
   ]
  }
 ]
}